insert into group_note values(1, 'The Tartar Steppe', 'description1');
insert into group_note values(2, 'Poem Strip', 'description2');
insert into group_note values(3,'Restless Nights: Selected Stories of Dino Buzzati','description3');
insert into group_note values(4,'ts: Selected Stories of Dino Buzzati','description3');
insert into group_note values(5,'Restlesof Dino Buzzati','description3');
insert into group_note values(6,'Restless Nights: Selected Stories of Dino Buzzati','description4');
insert into group_note values(7,'Restltories of Dino Buzzati','description3');
insert into group_note values(8,'Restless Nights: Selected Suzzati','description3');
insert into group_note values(9,'Restless Nights: Selected Stories of Dino Buzzati','yydescription6');
insert into group_note values(10,'Restless Nights: Selected Stories of Dino Buzzati','ssdescription3');
insert into group_note values(11,'Restless Nights: Selected Stories of Dino Buzzati','xxdescription7');
insert into note (id, title, description, group_note_id) values(1, 'tytul', 'description', 1);
insert into note (id, title, description, group_note_id) values(2, 'tytul2', 'xdescription2', 1);
insert into note (id, title, description, group_note_id) values(3, 'tytul3', 'rdescription3', 1);
insert into note (id, title, description, group_note_id) values(4, 'tytul4', 'description4', 2);